spring.application.name=tradex

# DATABASE CONFIG

spring.datasource.url=jdbc:postgresql://localhost:5432/tradex
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# MAIL CONFIG (Gmail SMTP - replace with your App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=varshneypiyush209@gmail.com
spring.mail.password=ywvk ibsb wbbu igrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false

# APP CONFIG
app.base-url=http://localhost:8080

# JWT CONFIG (change secret to a strong random value in production)
app.jwt-secret=tradex-super-secret-key-change-in-production-xxxx
app.jwt-expiry-ms=8640000

